### PR TITLE
Database

### PR DESCRIPTION
**Pull request by wells19d**

### CODE REVIEW

**Review by DavidVinson — COMMENTED** [review]
Database built collectively by the team. Have one question on the crop_status where the id starts at '2' rather than '1'.

**Comment by DavidVinson** [comment]
Trying to merge to master.

**Comment by wells19d** [comment]
Force merge

**Review by wells19d — COMMENTED** [review]
Updating database

**Comment by wells19d** [comment]
Submitting Review

**Review by DavidVinson — APPROVED** [review]

**Comment by DavidVinson** [comment]
Database has been reviewed. branch accepted.

**Pull request merged**
